### ISSUE TITLE
Fall 2017 Epic

### ISSUE THREAD

**Issue by cryptonym0** [trucsclub/trucsclub.github.io#131]
Online:

- [x] Update Website
- [ ] Set Up Help Lab Form
- [ ] Set up Elections
- [ ] Update domains WHOIS records @marcolussetti

Visuals:

- [ ] Print Business Cards
- [ ] Design/Print Banner
- [ ] Design/Print Help Lab Memes
- [x] Design/Print Back to School BBQ Memes
- [x] Design/Print Back to school BBQ Pamphets

Emails:

- [ ] Help Lab Email
- [ ] Back To School BBQ After Email
- [ ] Workshop Survey Email @marcolussetti + @snooglebunny

LANParty:

- [ ] Get A Venue and a Date Set Up - Amanda Chan

Workshops:

- [ ] Get Fall Github workshop rolling @marcolussetti
- [ ] Set up other fall workshops @marcolussetti
- [ ] Prepare survey on workshops @marcolussetti

BBQ:

- [x] Set Up Volunteer Schedual
- [x] Buy Doritos/mtn dew
- [x] Create and Print Memes
- [x] Have a good sign up system

Funds:

- [ ] Actually Deposit them
- [ ] Account for them

Inventory to Collect:

- [x] All sodipaps/bawls from mitch
- [x] Cords from mitch
- [ ] T-Shirts from Kevin
- [ ] Reb Bull from Elycia

Legal:

- [x] Change Signing Authorities
- [ ] Renew Club
- [ ] Renew Locker

Board Changes:

- [x] Get working E-mail from Marco
- [x] Remove all graduates from board

Nice to Haves:

- [ ] Links to All Lab Schedules on Website

**Comment by mitchhentges** [comment]
Cords and soda were dropped off at Kevin's office in the early summer

**Comment by marcolussetti** [comment]
I've added a couple of things as well, but should we move this list to the other repo where everyone has access?

**Comment by frogcrush** [comment]
I think we can close this issue as all tasks are currently on the other repo?
